# Generated by Django 5.1 on 2025-07-02 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_email_alter_customuser_mobile_number'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdoctor',
            name='specialization',
        ),
        migrations.AddField(
            model_name='userdoctor',
            name='speciality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctor.speciality'),
        ),
    ]
